name = "fish-submit"
main = "fish-submit.js"
compatibility_date = "2025-07-15"
workers_dev = true

[[kv_namespaces]]
binding = "KV"
id = "1bf9787e0d014e9a8aeb6e297e1ba76bc"

[vars]
CF_ACCOUNT_ID = ""
CF_API_TOKEN = ""
CF_IMAGE_NAMESPACE = ""
CSV_URL = ""
