name: Archive CSV Monthly

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs on the 1st of every month
  workflow_dispatch:      # Optional: manual trigger

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up archive folder and archive file
        run: |
          month=$(date -d "yesterday" +%Y-%m)
          mkdir -p csv/archive
          cp csv/submissions.csv csv/archive/archive-$month.csv
          echo "Archived to csv/archive/archive-$month.csv"

      - name: Reset current csv/submissions.csv
        run: |
          echo "Name,Fish Size,Date" > csv/submissions.csv

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add csv/archive/*.csv csv/submissions.csv
          git commit -m "Archive previous month to csv/archive and reset submissions.csv"
          git push
