name: Archive Monthly Winner
on:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install fs-extra node-fetch
      - name: Run archive script
        run: node archive-script.js
      - name: Commit changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add images/archive/*
          # Compute previous month for commit message
          PREV_MONTH=$(date -d "$(date +%Y-%m-01) -1 month" +"%B %Y")
          git commit -m "Archive winner for ${PREV_MONTH}" || echo "No changes to commit"
          git push
